class CheckboxSymbol:
	""" Valid Smartsheet checkbox symbol sets. """
	flag = "FLAG"
	star = "STAR"

class PicklistSymbol:
	""" Valid Smartsheet picklist symbol sets. """
	harveyBalls = "HARVEY_BALLS"
	redYellowGreen = "RYG"
	priority2Level = "PRIORITY"
	priority3Level = "PRIORITY_HML"
	decisionSymbol = "DECISION_SYMBOLS"
	decisionShape = "DECISION_SHAPES"
	stopPlayPauseForwardRewind = "VCR"
	redYellowGreenBlue = "RYGB"
	redYellowGreenGray = "RYGG"
	weatherIcon = "WEATHER"
	progressBar = "PROGRESS"
	arrow3Way = "ARROWS_3_WAY"
	arrow4Way = "ARROWS_4_WAY"
	arrow5Way = "ARROWS_5_WAY"
	direction3Way = "DIRECTIONS_3_WAY"
	direction4Way = "DIRECTIONS_4_WAY"
	skiDifficulty = "SKI"
	signalBar = "SIGNAL"
	starRating = "STAR_RATING"
	heartRating = "HEARTS"
	moneyRating = "MONEY"
	effortRating = "EFFORT"
	painFace = "PAIN"